### 00. fundamental of tensorflow Exercise


1.  Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [1]:
import datetime

print(datetime.datetime.now())

2026-01-25 22:46:19.751875


In [2]:
import tensorflow as tf

scaler =tf.constant(6)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [3]:
scaler.ndim

0

In [4]:
# creating a tensorflow vector of 1 dim
vector = tf.constant([1,5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 5], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# creating a tensorflow matrix
matrix = tf.constant([[4,7],
                     [4,9]], dtype=tf.float16)

In [7]:
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[4., 7.],
        [4., 9.]], dtype=float16)>,
 2)

###  2. Find the shape, rank and size of the tensors you created in 1.

In [8]:
# Shape, rank and size of the scaler

# let's create another scaler
scaler_0 = tf.constant(10)
scaler_0

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [9]:
print("Datatype of every element:", scaler_0.dtype)
print("Number of dimensions (rank):", scaler_0.ndim)
print("Shape of tensor:", scaler_0.shape)
print("size of the scaler:",  tf.size(scaler_0).numpy())

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 0
Shape of tensor: ()
size of the scaler: 1


In [10]:
# Shape, rank and size of the vector

# let's create another vector
vector_0 = tf.constant([5,9])
vector_0

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 9], dtype=int32)>

In [11]:
print("Datatype of every element:", vector_0 .dtype)
print("Number of dimensions (rank):", vector_0 .ndim)
print("Shape of tensor:", vector_0 .shape)
print("size of the scaler:",  tf.size(vector_0 ).numpy())

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 1
Shape of tensor: (2,)
size of the scaler: 2


In [12]:
# Shape, rank and size of the matrix

# let's create another matrix
matrix_0 = tf.constant([[2,5],
                        [3,8],
                        [23,56]], dtype=tf.float16)
matrix_0

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 2.,  5.],
       [ 3.,  8.],
       [23., 56.]], dtype=float16)>

In [13]:
print("Datatype of every element:", vector_0 .dtype)
print("Number of dimensions (rank):", vector_0 .ndim)
print("Shape of tensor:", vector_0 .shape)
print("size of the scaler:",  tf.size(vector_0 ).numpy())

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 1
Shape of tensor: (2,)
size of the scaler: 2


In [14]:
# let's create a tensor

tensor_3 =  tf.constant([[[[[1,3,4],
                           [4,2,6],
                           [6,4,7],
                           [2,6,3]],
                          [[2,6,4],
                          [6,8,2],
                          [1,3,4],
                           [7,9,2]],
                          [[2,1,6],
                           [3,7,2],
                           [4,7,8],
                           [2,5,6]]]]])

tensor_3

<tf.Tensor: shape=(1, 1, 3, 4, 3), dtype=int32, numpy=
array([[[[[1, 3, 4],
          [4, 2, 6],
          [6, 4, 7],
          [2, 6, 3]],

         [[2, 6, 4],
          [6, 8, 2],
          [1, 3, 4],
          [7, 9, 2]],

         [[2, 1, 6],
          [3, 7, 2],
          [4, 7, 8],
          [2, 5, 6]]]]], dtype=int32)>

In [15]:
tensor_3.ndim

5

In [16]:
print("Datatype of every element:", tensor_3 .dtype)
print("Number of dimensions (rank):", tensor_3 .ndim)
print("Shape of tensor:", tensor_3 .shape)
print("size of the tensor:",  tf.size(tensor_3 ).numpy())

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 5
Shape of tensor: (1, 1, 3, 4, 3)
size of the tensor: 36


## 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [17]:
# random tensor
tf.random.set_seed(42)
random_1 = tf.random.uniform(shape=(5,300))
random_1


<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
        0.03699052],
       [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
        0.2200619 ],
       [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
        0.00726748],
       [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
        0.9409125 ],
       [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
        0.44135118]], dtype=float32)>

In [18]:
print("Number of dimensions (rank):", random_1.ndim)
print("Shape of tensor:", random_1.shape)
print("size of the tensor:",  tf.size(random_1 ).numpy())

Number of dimensions (rank): 2
Shape of tensor: (5, 300)
size of the tensor: 1500


In [19]:
# lets create another tensor
tf.random.set_seed(42)
random_2 = tf.random.uniform(shape=(5,300))
random_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
        0.03699052],
       [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
        0.2200619 ],
       [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
        0.00726748],
       [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
        0.9409125 ],
       [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
        0.44135118]], dtype=float32)>

##  4.  Multiply the two tensors you created in 3 using matrix multiplication.

In [20]:
# multiply the two random tensro above

# tf.matmal(random_1, random_2)
tf.multiply(random_1, random_2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[4.4164279e-01, 1.9448698e-01, 1.2452606e-01, ..., 9.8661751e-02,
        5.7661778e-01, 1.3682988e-03],
       [2.8304955e-01, 8.4855378e-02, 1.1176224e-02, ..., 2.9216504e-01,
        9.8757625e-02, 4.8427239e-02],
       [7.0630698e-03, 1.3065366e-03, 9.5515686e-01, ..., 4.6296600e-02,
        9.5767713e-01, 5.2816195e-05],
       [5.4714793e-01, 4.4264695e-01, 6.2067290e-03, ..., 5.0662118e-01,
        4.9190181e-03, 8.8531631e-01],
       [2.5158225e-02, 1.4457737e-02, 7.4083231e-02, ..., 7.7878487e-01,
        2.0520218e-02, 1.9479086e-01]], dtype=float32)>

###   5. Multiply the two tensors you created in 3 using dot product.

In [21]:
random_1 * random_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[4.4164279e-01, 1.9448698e-01, 1.2452606e-01, ..., 9.8661751e-02,
        5.7661778e-01, 1.3682988e-03],
       [2.8304955e-01, 8.4855378e-02, 1.1176224e-02, ..., 2.9216504e-01,
        9.8757625e-02, 4.8427239e-02],
       [7.0630698e-03, 1.3065366e-03, 9.5515686e-01, ..., 4.6296600e-02,
        9.5767713e-01, 5.2816195e-05],
       [5.4714793e-01, 4.4264695e-01, 6.2067290e-03, ..., 5.0662118e-01,
        4.9190181e-03, 8.8531631e-01],
       [2.5158225e-02, 1.4457737e-02, 7.4083231e-02, ..., 7.7878487e-01,
        2.0520218e-02, 1.9479086e-01]], dtype=float32)>

## Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [22]:
tf.random.set_seed(42)
random_3 = tf.random.uniform(shape=(224,224,3))
random_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

##  7. Find the min and max values of the tensor you created in 6 along the first axis.

In [23]:
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[4., 7.],
       [4., 9.]], dtype=float16)>

In [24]:
import numpy as np
import tensorflow as tf

numpy_a = np.arange(1, 37, dtype=np.int32)  # 36 elements
tensor_a = tf.constant(numpy_a, shape=[2, 6, 3])
print(tensor_a)


tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]], shape=(2, 6, 3), dtype=int32)


In [25]:
# Find minimum value
min_value = tf.reduce_min(tensor_a)

# Find maximum value
max_value = tf.reduce_max(tensor_a)

print("Min:", min_value.numpy())
print("Max:", max_value.numpy())

Min: 1
Max: 36


## 7. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [26]:
tensor_5a = tf.random.uniform(shape=[1, 224, 224, 3], minval=0, maxval=1)
tensor_5a

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.68789124, 0.48447883, 0.9309944 ],
         [0.252187  , 0.73115396, 0.89256823],
         [0.94674826, 0.7493341 , 0.34925628],
         ...,
         [0.10315919, 0.9291539 , 0.99506986],
         [0.51019716, 0.9048054 , 0.22966433],
         [0.6319853 , 0.254349  , 0.6146672 ]],

        [[0.5757792 , 0.06120789, 0.41327834],
         [0.2947657 , 0.06683052, 0.8412062 ],
         [0.9196522 , 0.28208435, 0.88919353],
         ...,
         [0.8421594 , 0.92932725, 0.61236584],
         [0.9058645 , 0.48668993, 0.28548574],
         [0.30320632, 0.06468201, 0.79784656]],

        [[0.4406476 , 0.32621968, 0.03153896],
         [0.65943134, 0.43695068, 0.3716799 ],
         [0.7005588 , 0.81334114, 0.86623895],
         ...,
         [0.26015413, 0.7758442 , 0.32498944],
         [0.81527984, 0.906564  , 0.17323983],
         [0.65714204, 0.83752465, 0.18657303]],

        ...,

        [[0.4058814 , 0.8737236 , 

In [27]:
print("dimenesion: ", tensor_5a.ndim)
print("shape: ",  tensor_5a.shape)

dimenesion:  4
shape:  (1, 224, 224, 3)


In [29]:
# lets squeeze
tensor_6 = tf.squeeze(tensor_5a)
tensor_6

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.68789124, 0.48447883, 0.9309944 ],
        [0.252187  , 0.73115396, 0.89256823],
        [0.94674826, 0.7493341 , 0.34925628],
        ...,
        [0.10315919, 0.9291539 , 0.99506986],
        [0.51019716, 0.9048054 , 0.22966433],
        [0.6319853 , 0.254349  , 0.6146672 ]],

       [[0.5757792 , 0.06120789, 0.41327834],
        [0.2947657 , 0.06683052, 0.8412062 ],
        [0.9196522 , 0.28208435, 0.88919353],
        ...,
        [0.8421594 , 0.92932725, 0.61236584],
        [0.9058645 , 0.48668993, 0.28548574],
        [0.30320632, 0.06468201, 0.79784656]],

       [[0.4406476 , 0.32621968, 0.03153896],
        [0.65943134, 0.43695068, 0.3716799 ],
        [0.7005588 , 0.81334114, 0.86623895],
        ...,
        [0.26015413, 0.7758442 , 0.32498944],
        [0.81527984, 0.906564  , 0.17323983],
        [0.65714204, 0.83752465, 0.18657303]],

       ...,

       [[0.4058814 , 0.8737236 , 0.9235314 ],
        [0.52

In [30]:
print("dimenesion: ", tensor_6.ndim)
print("shape: ",  tensor_6.shape)

dimenesion:  3
shape:  (224, 224, 3)


In [35]:
tf.shape(tensor_6), tensor_6.shape

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([224, 224,   3], dtype=int32)>,
 TensorShape([224, 224, 3]))

###  9.  Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [38]:
len(np.random.randint(2,5,10))

10

In [43]:
np.arange(2,5,dtype=np.int16)

array([2, 3, 4], dtype=int16)

In [1]:
import numpy as np
import tensorflow as tf
tf.random.set_seed(42)
tensor_10a=tf.constant(np.arange(2,62, dtype=np.int16), shape=(2,3,10))
tensor_10a

<tf.Tensor: shape=(2, 3, 10), dtype=int16, numpy=
array([[[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48, 49, 50, 51],
        [52, 53, 54, 55, 56, 57, 58, 59, 60, 61]]], dtype=int16)>

In [2]:
tf.reduce_min(tensor_10a).numpy(), tf.reduce_max(tensor_10a).numpy()

(np.int16(2), np.int16(61))

In [3]:
# index of the maximum value
tf.where(tensor_10a == tf.reduce_max(tensor_10a))

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[1, 2, 9]])>

In [4]:
# index of the minimum value
tf.where(tensor_10a == tf.reduce_min(tensor_10a))

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[0, 0, 0]])>

## 10/ One-hot encode the tensor you created in 9.

In [6]:
tf.one_hot(tensor_10a, depth=10)

<tf.Tensor: shape=(2, 3, 10, 10), dtype=float32, numpy=
array([[[[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0.